<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Driver Funds & Pondo Ledger Statement &mdash; {{ date('Y-m-d') }}</title>
    <style>
        @page { margin: 8mm 10mm; size: auto; }
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { background: #fff; font-family: 'Segoe UI', system-ui, sans-serif; padding: 10mm; color: #111; font-size: 11px; }
        .logo { max-height: 50px; width: auto; display: block; margin: 0 auto 10px auto; }
        h1 { text-align: center; font-size: 18px; font-weight: 900; text-transform: uppercase; letter-spacing: .1em; margin-bottom: 3px; }
        .subtitle { text-align: center; font-size: 10px; color: #475569; font-weight: 700; letter-spacing: .1em; text-transform: uppercase; margin-bottom: 24px; }
        .meta-box { display: flex; justify-content: space-between; border-top: 2px solid #0f172a; border-bottom: 1px solid #0f172a; padding: 8px 0; margin-bottom: 20px; font-size: 10px; font-weight: 700; text-transform: uppercase; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 24px; font-size: 10px; }
        thead th { border-bottom: 1.5px solid #000; padding: 6px 8px; text-transform: uppercase; font-weight: 900; font-size: 9px; text-align: left; }
        thead th.right { text-align: right; }
        tbody tr { border-bottom: 1px solid #e2e8f0; }
        tbody tr:nth-child(even) { background-color: #f8fafc; }
        td { padding: 6px 8px; vertical-align: middle; }
        td.right { text-align: right; font-weight: 700; }
        .type-deposit { color: #047857; font-weight: 900; }
        .type-damage { color: #b91c1c; font-weight: 900; }
        .type-maint { color: #b45309; font-weight: 900; }
        .type-other { color: #475569; font-weight: 700; }
        .footer { text-align: center; margin-top: 30px; padding-top: 12px; border-top: 1px dashed #cbd5e1; font-size: 9px; color: #64748b; }
    </style>
</head>
<body onload="window.print()">
    <img src="{{ asset('image/logo.png') }}" alt="Euro Taxi System" class="logo">
    <h1>Driver Savings & Pondo Ledger Statement</h1>
    <p class="subtitle">Official Audit Trail &mdash; Emergency Funds, Damage Deductions & Disbursements</p>

    <div class="meta-box">
        <div>Statement Scope: {{ $driver ? $driver->full_name . ' (' . ($driver->license_number ?: 'No Lic') . ')' : 'System-Wide Ledger' }}</div>
        <div>Generated: {{ date('F d, Y h:i A') }}</div>
        <div>Total Records: {{ count($transactions) }}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Driver</th>
                <th>Unit</th>
                <th>Type</th>
                <th>Purpose / Incident Details</th>
                <th class="right">Amount</th>
                <th class="right">Balance After</th>
                <th>Encoder</th>
            </tr>
        </thead>
        <tbody>
            @forelse($transactions as $t)
            <tr>
                <td>{{ \Carbon\Carbon::parse($t->date)->format('M d, Y') }}</td>
                <td style="font-weight: 800;">{{ $t->driver_name }}</td>
                <td>{{ $t->shift_plate ?: '—' }}</td>
                <td>
                    @if($t->type === 'deposit')
                        <span class="type-deposit">Boundary Pondo</span>
                    @elseif($t->type === 'damage_deduction')
                        <span class="type-damage">Bangga / Damage</span>
                    @elseif($t->type === 'maintenance_share')
                        <span class="type-maint">Maint Share</span>
                    @elseif($t->type === 'company_liability')
                        <span class="type-other">Debt Settlement</span>
                    @else
                        <span class="type-other">Driver Cashout</span>
                    @endif
                </td>
                <td>{{ $t->description ?: 'Shift fund record' }}</td>
                <td class="right">
                    @if($t->type === 'deposit')
                        +₱{{ number_format($t->amount, 2) }}
                    @else
                        -₱{{ number_format($t->amount, 2) }}
                    @endif
                </td>
                <td class="right">₱{{ number_format($t->balance_after, 2) }}</td>
                <td>{{ $t->creator_name ?: 'System' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="8" style="text-align: center; padding: 20px; color: #94a3b8;">No ledger transactions recorded.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Euro Taxi Management System &bull; Generated by {{ auth()->user()->name ?? 'Administrator' }} &bull; Confirmed Official Record
    </div>
</body>
</html>
